### PR TITLE
Remove other site pages

### PR DESCRIPTION
**Pull request by StevenMaude**
Remove pages from quickcode.io and pdftables.com

These were collected by wget following redirects.

### CODE REVIEW

**Comment by StevenMaude** [comment]
Not sure if the redirects will work correctly; they'd need testing ideally.

(i.e. since we've removed these pages, do the URLs on the site now go to the correct place).

They may need fixing up either in the redirects or in the HTML.

**Comment by StevenMaude** [comment]
@frabcus I rebased this so it can now be merged if you're happy with it.

**Comment by StevenMaude** [comment]
```
products/code-in-browser.html OK
https://scraperwiki.com/products/data-science-platform.html NOT OK
https://scraperwiki.com/tools/code-in-browser.html NOT OK
tools/tablextract.1.html OK
tools/tablextract.html OK
tools/tablextract/index.html OK
```

The NOT OK URLs need redirecting before we remove them.

**Comment by StevenMaude** [comment]
Can merge this once https://github.com/sensiblecodeio/salt-data/pull/364 is merged.

It redirects the two URLs mentioned above.

**Comment by pwaller** [comment]
I'm unsure how to test this, or what I'm reviewing (I mean 'test' in the broadest sense, not just "running it"). You should just self-merge here, or if you want me to weigh in, I will need more background. It seems fine to me from what I can see, but I'm not in this head-space.

**Pull request merged**
